version: 2.1
jobs:
  build:
    docker:
      - image: samsoir/alpine-shunit2:1.2
        auth:
          username: samsoir
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Golang
          command: |
            bash install.sh
            ln -s /usr/local/go/bin/go /usr/local/bin/go
            echo $PATH
      - run:
          name: Verfiy Go installed
          command: |
            ls -la /usr/local/go/bin
            go version
      - run:
          name: Test Golang Version installed
          command: |
            examples/test_go_version.sh
