version: 2.1
jobs:
  test:
    docker:
      - image: samsoir/debian-shunit2:1.0
        auth:
          username: samsoir
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Golang
          command: |
            bash install.sh
            ln -s /usr/local/go/bin/go /usr/local/bin/go
      - run:
          name: Test Golang Version installed
          command: |
            examples/test_go_version.sh
workflows:
  version: 2
  test:
    jobs:
      - test
