version: 2.1
jobs:
  build:
    docker:
      - image: samsoir/alpine-shunit2:1.2
        auth:
          username: samsoir
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Golang
          command: |
            bash install.sh
      - run:
          name: Run Example Test
          command: |
            examples/equality_test.sh
